# Generated by Django 3.2.7 on 2021-09-10 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
